name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 8 * * 1-5"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: 'action-required'
        stale-pr-label: 'action-required'
        only-labels: 'triage'
        days-before-stale: 2
        days-before-close: -1

