name: Notify users based on issue labels

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.2
          with:
             repo-token: ${{ secrets.GITHUB_TOKEN }}
             recipients: |
                  action-required=@Azure/aks-pm
