name: "Close stale issues"
on:
  schedule:
  - cron: "0,30 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had activity in 90 days. It will be closed in 30 days if no further activity occurs. Thank you!'
        close-issue-message: 'This issue has been stale for 30 days without any activity. It will now be closed. If you have any issues or suggestions please open a new issue.'
        stale-issue-label: 'stale'
        exempt-issue-labels: 'pinned,security,feature,roadmap,enhancement,feature-request,bug'
        remove-stale-when-updated: true
        days-before-stale: 90
        days-before-close: 30
